### ISSUE TITLE
The last image shows through before loading

### ISSUE THREAD

**Issue by dccreatives** [kthornbloom/Smoothslides#10]
I see that the last slide shows for a split second, before the slideshow completely loads. I noticed it on your demo as well.

**Comment by kthornbloom** [comment]
Sorry to respond so late! This is because each animation starts by fading the next image in. In order to keep the images in the correct order, the last image is actually appended as the first so that the 'real' first can fade in and animate. Maybe not the best solution, but I'm open to alternate ideas!

**Comment by dccreatives** [comment]
If I place a white bg behind it, will that help? 

 

Thank You,

 

Hendy Zucker // President

 

DotCom Creatives

www.dccreatives.com // 732.901.0433

**Comment by kthornbloom** [comment]
I'm sorry, but placing a white background won't work. Basically, because each animation starts with a fade-in, you'll see the previous slide for a second until the new one has fully faded in.
