### ISSUE TITLE
Jumpy When Full Width

### ISSUE THREAD

**Issue by digitaldreamsol** [kthornbloom/Smoothslides#13]
I am trying to use smoothslides fullwidth but for some reason the image loads full width then jumps to fit. I tried the large images in the demo and the 'jump' from full image to image fit still happened. Is this because of the size of the images are big in comparison to the test images? I can send you a pm with a link to show you what is happening if required.

**Comment by digitaldreamsol** [comment]
http://www.247design.co.uk/Smoothslides-master/index.html

**Comment by digitaldreamsol** [comment]
Firefox 38.0.5

**Comment by kthornbloom** [comment]
I think it's because the images are gigantic. Here's what I'd recommend to you (or anyone else looking to use this plugin at full width, no matter what size the images are).

- Re-save your images at the same aspect ratio, but a smaller size. 
- Use the non minified version of the script<br>
    `<script type="text/javascript" src="js/smoothslides-2.0.0.js"></script>`
- Within that file, comment out line 33<br>
    `//$('#'+uniqueId).css('maxWidth',maxWidth);`
- In smoothslides.theme.css, change line 81 from max-width to just width<br>
    `width:100%;`
- On line 73, find the .ss-slide class and add<br>
   ` width:100%;`

This will scale up your images if they are smaller than the area you want them to fill. I may add a 'fullWidth' option in the near future to prevent the need to do this.

**Comment by digitaldreamsol** [comment]
Many thanks for you help with this. I will give this go and feedback how I get on :)

**Comment by digitaldreamsol** [comment]
The only issue on a full width is on zoomin and zoomout the lower image shows in the corner: http://www.247design.co.uk/Smoothslides-master3/index.html

On a different note which isnt an issue, I dont know if its possible but from a design aspect it would be great to have a max-height for the slide for desktops, tablets etc with some sort of increase in the ken burns effect to offset the height?

**Comment by kthornbloom** [comment]
Hi there. If you don't mind updating to  <a href="http://kthornbloom.github.io/Smoothslides/">version 2.1.0</a>, I have added a new option called matchImageSize which can be set to 'false' to enable it to be grow larger than the image size. I also made some changes that may help with the 'jumpyness'! Don't forget to update the CSS as well.
